exports.PATHS={
    users:"/api/users",
    business:"/api/business",
    jobs: "/api/jobs",
    admin:"/api/admin",
    login: '/login',
    verifyLoginCode: '/login-code',
    getCodeInfoById: "/login-code/:codeID",
    verifyEmailCode: '/email-code',
    email: "/email",
    setupProfile: '/profile-setup',
    profile:'/profile',
    businessApply: "/",
    userID: "/:userID",
    archiveJob: "/:jobID/archive",
    jobID: "/:jobID",
    adminBusiness:"/business/:businessID",
    acceptBusiness:"/:businessID/accept",
    declineBusiness:"/:businessID/decline",
    profilePicture:"/profile-picture",
    files:"/file",
    file:"/file/:fileID",
    me:"/me",
    messages:"/api/messages",
    pendingBusinesses:"/pending-businesses",
    message:"/:messageID",
    businesses:'/businesses',
    businessID:"/:businessID",
    acceptEditBusiness:"/:businessID/accept-edit",
    declineEditBusiness:"/:businessID/decline-edit",
    editBusiness:"/:businessID/edit",
    makeAdmin:"/make",
    adminEmail:"/:email",
    approveJob: "/jobs/:jobID/accept",
    declineJob: "/jobs/:jobID/decline"
}