exports.PATHS={
    users:"/api/users",
    business:"/api/business",
    jobs: "/api/jobs",
    admin:"/api/admin",
    login: '/login',
    verifyLoginCode: '/login-code',
    getCodeInfoById: "/login-code/:codeID",
    verifyEmailCode: '/email-code',
    email: "/email",
    setupProfile: '/profile-setup',
    profile:'/profile',
    businessApply: "/",
    userID: "/:userID",
    archiveJob: "/:jobID/archive",
    jobID: "/:jobID",
    adminBusiness:"/:businessID",
    acceptBusiness:"/:businessID/accept",
    declineBusiness:"/:businessID/decline",
}